from django.db import models

class ModelData(models.Model):
    marital_status = models.IntegerField()
    application_mode = models.IntegerField()
    application_order = models.IntegerField()
    course = models.IntegerField()
    daytime_evening_attendance = models.IntegerField()
    previous_qualification = models.IntegerField()
    nationality = models.IntegerField()
    mothers_qualification = models.IntegerField()
    fathers_qualification = models.IntegerField()
    mothers_occupation = models.IntegerField()
    fathers_occupation = models.IntegerField()
    displaced = models.IntegerField()
    educational_special_needs = models.IntegerField()
    debtor = models.IntegerField()
    tuition_fees_up_to_date = models.IntegerField()
    gender = models.IntegerField()
    scholarship_holder = models.IntegerField()
    age_at_enrollment = models.IntegerField()
    international = models.IntegerField()
    curricular_units_1st_sem_credited = models.IntegerField()
    curricular_units_1st_sem_enrolled = models.IntegerField()
    curricular_units_1st_sem_evaluations = models.IntegerField()
    curricular_units_1st_sem_approved = models.IntegerField()
    curricular_units_1st_sem_grade = models.IntegerField()
    curricular_units_1st_sem_without_evaluations = models.IntegerField()
    curricular_units_2nd_sem_credited = models.IntegerField()
    curricular_units_2nd_sem_enrolled = models.IntegerField()
    curricular_units_2nd_sem_evaluations = models.IntegerField()
    curricular_units_2nd_sem_approved = models.IntegerField()
    curricular_units_2nd_sem_grade = models.IntegerField()
    curricular_units_2nd_sem_without_evaluations = models.IntegerField()
    unemployment_rate = models.FloatField()
    inflation_rate = models.FloatField()
    gdp = models.FloatField()

    def __str__(self):
        return f"ModelData object ({self.id})"