# serializers.py
from rest_framework import serializers

class PredictionInputSerializer(serializers.Serializer):
    # Define serializer fields based on the extracted feature names
    marital_status = serializers.IntegerField()
    application_mode = serializers.IntegerField()
    application_order = serializers.IntegerField()
    course = serializers.IntegerField()
    daytime_evening_attendance = serializers.IntegerField()
    previous_qualification = serializers.IntegerField()
    nationality = serializers.IntegerField()
    mothers_qualification = serializers.IntegerField()
    fathers_qualification = serializers.IntegerField()
    mothers_occupation = serializers.IntegerField()
    fathers_occupation = serializers.IntegerField()
    displaced = serializers.IntegerField()
    educational_special_needs = serializers.IntegerField()
    debtor = serializers.IntegerField()
    tuition_fees_up_to_date = serializers.IntegerField()
    gender = serializers.IntegerField()
    scholarship_holder = serializers.IntegerField()
    age_at_enrollment = serializers.IntegerField()
    international = serializers.IntegerField()
    curricular_units_1st_sem_credited = serializers.IntegerField()
    curricular_units_1st_sem_enrolled = serializers.IntegerField()
    curricular_units_1st_sem_evaluations = serializers.IntegerField()
    curricular_units_1st_sem_approved = serializers.IntegerField()
    curricular_units_1st_sem_grade = serializers.FloatField()
    curricular_units_1st_sem_without_evaluations = serializers.IntegerField()
    curricular_units_2nd_sem_credited = serializers.IntegerField()
    curricular_units_2nd_sem_enrolled = serializers.IntegerField()
    curricular_units_2nd_sem_evaluations = serializers.IntegerField()
    curricular_units_2nd_sem_approved = serializers.IntegerField()
    curricular_units_2nd_sem_grade = serializers.FloatField()
    curricular_units_2nd_sem_without_evaluations = serializers.IntegerField()
    unemployment_rate = serializers.FloatField()
    inflation_rate = serializers.FloatField()
    gdp = serializers.FloatField()
